"""Handle pull_request webhook events — auto-review via codesense-ai."""

from __future__ import annotations

from typing import Any

import httpx
import structlog

from config import settings
from orchestrator.memory import memory

log = structlog.get_logger()

_http = httpx.AsyncClient(timeout=120.0)

PR_COMMENT_TEMPLATE = """\
## 🤖 OmniMed-Nexus Code Review

> Powered by **codesense-ai** — multi-agent review across security, performance, architecture, tests & docs.

{review_body}

---
*Auto-generated by [omnimed-nexus](https://github.com/{nexus_repo}). \
To re-trigger: comment `/review`.*
"""


async def handle_pr_event(payload: dict[str, Any], token: str) -> None:
    action = payload.get("action")
    if action not in ("opened", "synchronize", "reopened"):
        return

    pr = payload["pull_request"]
    repo_full = payload["repository"]["full_name"]
    pr_number = pr["number"]
    pr_title = pr["title"]
    diff_url = pr["diff_url"]

    log.info("pr_review_triggered", repo=repo_full, pr=pr_number, action=action)

    # Fetch diff
    diff_resp = await _http.get(
        diff_url,
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github.v3.diff"},
    )
    diff_text = diff_resp.text if diff_resp.status_code == 200 else ""

    # Call codesense-ai
    try:
        review_resp = await _http.post(
            f"{settings.codesense_api_url}/review",
            json={
                "code": diff_text,
                "language": "diff",
                "context": f"PR #{pr_number}: {pr_title} in {repo_full}",
            },
        )
        review_data = review_resp.json() if review_resp.status_code == 200 else {"error": "codesense-ai unavailable"}
    except httpx.HTTPError as e:
        review_data = {"error": str(e)}

    review_body = _format_review(review_data)
    comment_body = PR_COMMENT_TEMPLATE.format(
        review_body=review_body,
        nexus_repo=settings.nexus_repo,
    )

    # Post comment to PR
    await _http.post(
        f"https://api.github.com/repos/{repo_full}/issues/{pr_number}/comments",
        json={"body": comment_body},
        headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"},
    )

    # Store finding in Neo4j if there are issues
    if review_data.get("issues"):
        for issue in review_data["issues"][:5]:  # top 5 issues
            await memory.store_finding(
                repo=repo_full,
                finding_type="code_issue",
                description=issue.get("description", str(issue)),
                severity=issue.get("severity", "medium"),
                metadata={"pr": pr_number, "title": pr_title},
            )

    log.info("pr_review_posted", repo=repo_full, pr=pr_number)


def _format_review(data: dict[str, Any]) -> str:
    if "error" in data:
        return f"⚠️ Review unavailable: `{data['error']}`"

    lines: list[str] = []

    scores = data.get("scores", {})
    if scores:
        lines.append("### Scores")
        for category, score in scores.items():
            emoji = "✅" if score >= 8 else "⚠️" if score >= 5 else "❌"
            lines.append(f"- {emoji} **{category.title()}**: {score}/10")
        lines.append("")

    issues = data.get("issues", [])
    if issues:
        lines.append(f"### Issues Found ({len(issues)})")
        for i in issues[:10]:
            sev = i.get("severity", "medium")
            icon = "🔴" if sev == "critical" else "🟠" if sev == "high" else "🟡"
            lines.append(f"- {icon} **{sev.upper()}** — {i.get('description', str(i))}")
        lines.append("")

    suggestions = data.get("suggestions", [])
    if suggestions:
        lines.append("### Suggestions")
        for s in suggestions[:5]:
            lines.append(f"- 💡 {s}")

    return "\n".join(lines) if lines else "No significant issues found. ✅"
